name=Tiseg
version=0.1
authors=3A
maintainers=3A
sentence=A simple timer library for GyverSegment display.
paragraph=This library simplifies creating blinking countdown timers using multi-digit seven-segment displays and a button.
category=Display
url=
architectures=*
depends=GyverSegment, GyverIO
